package org.drools.ansible.rulebook.integration.ha.postgres;

import static org.drools.ansible.rulebook.integration.ha.api.HATableNames.ACTION_INFO;
import static org.drools.ansible.rulebook.integration.ha.api.HATableNames.HA_STATS;
import static org.drools.ansible.rulebook.integration.ha.api.HATableNames.IDX_ACTION_INFO_ME;
import static org.drools.ansible.rulebook.integration.ha.api.HATableNames.IDX_MATCHING_EVENT_HA_UUID;
import static org.drools.ansible.rulebook.integration.ha.api.HATableNames.MATCHING_EVENT;
import static org.drools.ansible.rulebook.integration.ha.api.HATableNames.SESSION_STATE;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;

import javax.sql.DataSource;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * PostgreSQL database schema creation and management
 */
public class PostgreSQLSchema {

    private static final Logger logger = LoggerFactory.getLogger(PostgreSQLSchema.class);

    // Advisory lock key for schema DDL serialization (hash of "drools_ansible_schema")
    private static final long SCHEMA_ADVISORY_LOCK_KEY = 7_370_292_001L;

    public static void createSchema(DataSource dataSource) throws SQLException {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {

            conn.setAutoCommit(false);
            try {
                // Acquire transaction-level advisory lock to serialize concurrent DDL.
                // PostgreSQL's CREATE TABLE IF NOT EXISTS can race on pg_type catalog
                // when two transactions execute it simultaneously.
                stmt.execute("SELECT pg_advisory_xact_lock(" + SCHEMA_ADVISORY_LOCK_KEY + ")");

                // Create session state table
                // PostgreSQL differences from H2:
                // - BIGSERIAL instead of BIGINT GENERATED BY DEFAULT AS IDENTITY
                // - TEXT instead of CLOB
                String createSessionStateTable =
                        "CREATE TABLE IF NOT EXISTS " + SESSION_STATE + " ("
                        + "id BIGSERIAL PRIMARY KEY, "
                        + "ha_uuid VARCHAR(255) NOT NULL, "
                        + "rule_set_name VARCHAR(255) NOT NULL, "
                        + "rulebook_hash VARCHAR(64), "
                        + "partial_matching_events TEXT, "
                        + "processed_event_ids TEXT, "
                        + "persisted_time TIMESTAMP, "
                        + "current_state_sha VARCHAR(64), "
                        + "created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, "
                        + "leader_id VARCHAR(255), "
                        + "metadata JSONB DEFAULT '{}'::jsonb, "
                        + "properties JSONB DEFAULT '{}'::jsonb, "
                        + "settings JSONB DEFAULT '{}'::jsonb, "
                        + "ext JSONB DEFAULT '{}'::jsonb, "
                        + "UNIQUE(ha_uuid, rule_set_name)"
                        + ")";
                stmt.execute(createSessionStateTable);

                // Create MatchingEvent table
                // PostgreSQL differences from H2:
                // - UUID instead of VARCHAR(36) for native UUID support
                // - TEXT instead of CLOB
                String createMatchingEventTable =
                        "CREATE TABLE IF NOT EXISTS " + MATCHING_EVENT + " ("
                        + "me_uuid UUID PRIMARY KEY, "
                        + "ha_uuid VARCHAR(255) NOT NULL, "
                        + "rule_set_name VARCHAR(255), "
                        + "rule_name VARCHAR(255) NOT NULL, "
                        + "event_data TEXT, "
                        + "created_at BIGINT DEFAULT 0, "
                        + "metadata JSONB DEFAULT '{}'::jsonb, "
                        + "properties JSONB DEFAULT '{}'::jsonb, "
                        + "settings JSONB DEFAULT '{}'::jsonb, "
                        + "ext JSONB DEFAULT '{}'::jsonb"
                        + ")";
                stmt.execute(createMatchingEventTable);

                // Create ActionInfo table
                // PostgreSQL differences from H2:
                // - UUID instead of VARCHAR(36) for native UUID support
                // - TEXT instead of CLOB
                String createActionInfoTable =
                        "CREATE TABLE IF NOT EXISTS " + ACTION_INFO + " ("
                        + "id UUID PRIMARY KEY, "
                        + "ha_uuid VARCHAR(255) NOT NULL, "
                        + "me_uuid UUID NOT NULL, "
                        + "index INT NOT NULL, "
                        + "action_data TEXT, "
                        + "metadata JSONB DEFAULT '{}'::jsonb, "
                        + "properties JSONB DEFAULT '{}'::jsonb, "
                        + "settings JSONB DEFAULT '{}'::jsonb, "
                        + "ext JSONB DEFAULT '{}'::jsonb, "
                        + "UNIQUE(me_uuid, index), "
                        + "FOREIGN KEY (me_uuid) REFERENCES " + MATCHING_EVENT + "(me_uuid) ON DELETE CASCADE"
                        + ")";
                stmt.execute(createActionInfoTable);

                String createMatchingEventIndex =
                        "CREATE INDEX IF NOT EXISTS " + IDX_MATCHING_EVENT_HA_UUID
                        + " ON " + MATCHING_EVENT + "(ha_uuid)";
                stmt.execute(createMatchingEventIndex);

                String createActionInfoIndex =
                        "CREATE INDEX IF NOT EXISTS " + IDX_ACTION_INFO_ME
                        + " ON " + ACTION_INFO + "(me_uuid)";
                stmt.execute(createActionInfoIndex);

                // Create HA stats table
                // All stat fields are stored in a single 'properties' JSONB column.
                // ha_uuid (query key), updated_at (diagnostics), and extensibility columns remain.
                String createHAStatsTable =
                        "CREATE TABLE IF NOT EXISTS " + HA_STATS + " ("
                        + "id BIGSERIAL PRIMARY KEY, "
                        + "ha_uuid VARCHAR(255) NOT NULL UNIQUE, "
                        + "properties JSONB DEFAULT '{}'::jsonb, "
                        + "updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, "
                        + "metadata JSONB DEFAULT '{}'::jsonb, "
                        + "settings JSONB DEFAULT '{}'::jsonb, "
                        + "ext JSONB DEFAULT '{}'::jsonb"
                        + ")";
                stmt.execute(createHAStatsTable);

                conn.commit();

                // PostgreSQL emits NOTICE "relation X already exists, skipping" for IF NOT EXISTS.
                // JDBC surfaces these as SQLWarning. If present, tables were already created by another process.
                SQLWarning warning = stmt.getWarnings();
                if (warning != null) {
                    logger.info("PostgreSQL schema already exists (tables were likely created by another process)");
                } else {
                    logger.info("PostgreSQL schema created successfully");
                }
            } catch (SQLException e) {
                conn.rollback();
                throw e;
            }
        }
    }

    /**
     * Migrate existing tables to add extensibility columns.
     * PostgreSQL supports ADD COLUMN IF NOT EXISTS.
     */
    public static void migrateSchema(DataSource dataSource) throws SQLException {
        String[] tables = {SESSION_STATE, MATCHING_EVENT, ACTION_INFO, HA_STATS};
        String[] columns = {"metadata", "properties", "settings", "ext"};

        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {

            conn.setAutoCommit(false);
            try {
                stmt.execute("SELECT pg_advisory_xact_lock(" + SCHEMA_ADVISORY_LOCK_KEY + ")");

                for (String table : tables) {
                    for (String column : columns) {
                        stmt.execute("ALTER TABLE " + table + " ADD COLUMN IF NOT EXISTS " + column + " JSONB DEFAULT '{}'::jsonb");
                    }
                }

                // Migration: drop version column and update UNIQUE constraint
                // Step 1: Drop old constraint (PG naming convention: table_col1_col2_..._key)
                stmt.execute("ALTER TABLE " + SESSION_STATE + " DROP CONSTRAINT IF EXISTS " + SESSION_STATE + "_ha_uuid_rule_set_name_version_key");
                // Step 2: Drop version column
                stmt.execute("ALTER TABLE " + SESSION_STATE + " DROP COLUMN IF EXISTS version");
                // Step 3: Add new unique constraint (idempotent via CREATE UNIQUE INDEX IF NOT EXISTS)
                stmt.execute("CREATE UNIQUE INDEX IF NOT EXISTS uq_session_state_ha_ruleset ON " + SESSION_STATE + " (ha_uuid, rule_set_name)");

                conn.commit();
                logger.debug("PostgreSQL schema migration completed");
            } catch (SQLException e) {
                conn.rollback();
                throw e;
            }
        }
    }

    public static void dropSchema(DataSource dataSource) throws SQLException {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {

            conn.setAutoCommit(false);
            try {
                // Drop in reverse order due to foreign keys
                stmt.execute("DROP TABLE IF EXISTS " + ACTION_INFO + " CASCADE");
                stmt.execute("DROP TABLE IF EXISTS " + MATCHING_EVENT + " CASCADE");
                stmt.execute("DROP TABLE IF EXISTS " + SESSION_STATE + " CASCADE");
                stmt.execute("DROP TABLE IF EXISTS " + HA_STATS + " CASCADE");

                conn.commit();
                logger.info("PostgreSQL schema dropped successfully");
            } catch (SQLException e) {
                conn.rollback();
                throw e;
            }
        }
    }
}
